"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ["love.png", "refresh.png", "gitIco.png"]
OPTIONS = {
    'argv_emulation': True
    ,
    'iconfile' : 'gitIco.png'
}

setup(
    app=APP,
    name="GitHub Stray",
    data_files=DATA_FILES,
    version="1.1",
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
